# Generated by Django 4.1.3 on 2022-12-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_adress_listing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='time',
            new_name='title',
        ),
    ]
